CREATE TYPE "Role" AS ENUM ('PLATFORM_ADMIN', 'COMPANY_ADMIN', 'AGENT');
CREATE TYPE "ConnectionStatus" AS ENUM ('DISCONNECTED', 'QR_PENDING', 'CONNECTED', 'RECONNECTING');
CREATE TYPE "ConversationStatus" AS ENUM ('BOT_WAITING', 'HUMAN_WAITING', 'HUMAN_ACTIVE', 'CLOSED');
CREATE TYPE "MessageDirection" AS ENUM ('INBOUND', 'OUTBOUND');
CREATE TYPE "MessageKind" AS ENUM ('TEXT', 'IMAGE', 'DOCUMENT', 'AUDIO', 'SYSTEM');

CREATE TABLE "Company" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Company_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Company_slug_key" ON "Company"("slug");
CREATE TABLE "User" ("id" TEXT NOT NULL, "companyId" TEXT, "name" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'AGENT', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Sector" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "name" TEXT NOT NULL, "color" TEXT NOT NULL DEFAULT '#8AFF80', CONSTRAINT "Sector_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Sector_companyId_name_key" ON "Sector"("companyId", "name");
CREATE TABLE "WhatsAppConnection" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "label" TEXT NOT NULL, "jid" TEXT, "status" "ConnectionStatus" NOT NULL DEFAULT 'DISCONNECTED', "lastError" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WhatsAppConnection_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "WhatsAppConnection_companyId_label_key" ON "WhatsAppConnection"("companyId", "label");
CREATE TABLE "AuthSession" ("id" TEXT NOT NULL, "connectionId" TEXT NOT NULL, "key" TEXT NOT NULL, "value" JSONB NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AuthSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "AuthSession_connectionId_key_key" ON "AuthSession"("connectionId", "key");
CREATE TABLE "Contact" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "remoteJid" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT, "email" TEXT, "labels" TEXT[] DEFAULT ARRAY[]::TEXT[], "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Contact_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Contact_companyId_remoteJid_key" ON "Contact"("companyId", "remoteJid");
CREATE TABLE "Conversation" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "contactId" TEXT NOT NULL, "assignedUserId" TEXT, "sectorId" TEXT, "status" "ConversationStatus" NOT NULL DEFAULT 'BOT_WAITING', "botStep" TEXT, "botStepExpiresAt" TIMESTAMP(3), "unreadCount" INTEGER NOT NULL DEFAULT 0, "lastMessageAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Conversation_companyId_status_lastMessageAt_idx" ON "Conversation"("companyId", "status", "lastMessageAt");
CREATE TABLE "Message" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "connectionId" TEXT NOT NULL, "providerId" TEXT NOT NULL, "direction" "MessageDirection" NOT NULL, "kind" "MessageKind" NOT NULL DEFAULT 'TEXT', "body" TEXT, "mediaUrl" TEXT, "senderJid" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Message_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Message_connectionId_providerId_key" ON "Message"("connectionId", "providerId");
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId", "createdAt");
CREATE TABLE "InternalNote" ("id" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "authorId" TEXT NOT NULL, "body" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "InternalNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ConversationEvent" ("id" TEXT NOT NULL, "conversationId" TEXT NOT NULL, "type" TEXT NOT NULL, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ConversationEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BotConfig" ("id" TEXT NOT NULL, "companyId" TEXT NOT NULL, "enabled" BOOLEAN NOT NULL DEFAULT true, "welcomeMessage" TEXT NOT NULL DEFAULT 'Olá! Como podemos ajudar?', "fallbackMessage" TEXT NOT NULL DEFAULT 'Não entendi. Escolha uma opção do menu para continuar.', "afterHoursMessage" TEXT NOT NULL DEFAULT 'Estamos fora do horário. Retornaremos em breve.', "menu" JSONB NOT NULL, "businessHours" JSONB NOT NULL, "timezone" TEXT NOT NULL DEFAULT 'America/Sao_Paulo', "stepTtlMinutes" INTEGER NOT NULL DEFAULT 30, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BotConfig_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "BotConfig_companyId_key" ON "BotConfig"("companyId");

ALTER TABLE "User" ADD CONSTRAINT "User_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Sector" ADD CONSTRAINT "Sector_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WhatsAppConnection" ADD CONSTRAINT "WhatsAppConnection_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuthSession" ADD CONSTRAINT "AuthSession_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "WhatsAppConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Contact" ADD CONSTRAINT "Contact_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_contactId_fkey" FOREIGN KEY ("contactId") REFERENCES "Contact"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_assignedUserId_fkey" FOREIGN KEY ("assignedUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Conversation" ADD CONSTRAINT "Conversation_sectorId_fkey" FOREIGN KEY ("sectorId") REFERENCES "Sector"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Message" ADD CONSTRAINT "Message_connectionId_fkey" FOREIGN KEY ("connectionId") REFERENCES "WhatsAppConnection"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InternalNote" ADD CONSTRAINT "InternalNote_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InternalNote" ADD CONSTRAINT "InternalNote_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ConversationEvent" ADD CONSTRAINT "ConversationEvent_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BotConfig" ADD CONSTRAINT "BotConfig_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE CASCADE;
